"""Export sacremoses 0.2.0 Unicode classes as portable Python constants.

NeMo's detokenizer uses frozen Perl character classes, not Python's version-
dependent Unicode categories. Only development needs sacremoses.
"""
from importlib.metadata import version
from pathlib import Path
from sacremoses import MosesDetokenizer


def ranges(characters):
    result = []
    for c in sorted(set(map(ord, characters))):
        if result and c == result[-1][1] + 1:
            result[-1][1] = c
        else:
            result.append([c, c])
    return tuple(map(tuple,result))


if __name__ == '__main__':
    if version('sacremoses') != '0.2.0':
        raise RuntimeError('Requires sacremoses==0.2.0')
    root = Path(__file__).resolve().parents[1]
    text = '''# Character data from sacremoses 0.2.0 (MIT).
# Copyright (c) 2020 alvations. See LICENSE-SACREMOSES.
# Generated by tools/export_detokenizer.py; do not use Python Unicode classes
# here: their membership changes with the interpreter version.
'''
    text += 'ALPHA_RANGES = ' + repr(ranges(MosesDetokenizer.IsAlpha)) + '\n'
    text += 'CURRENCY_SYMBOLS = ' + ascii(MosesDetokenizer.IsSc) + '\n'
    (root/'kitten_text_processing/_unicode_data.py').write_text(text)
