"""Regenerate the C++ copy of the shared, frozen Sacremoses character tables."""
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from kitten_text_processing._unicode_data import ALPHA_RANGES, CURRENCY_SYMBOLS

path = ROOT/'cpp/src/unicode_data.hpp'
text = '// Generated by tools/export_cpp_unicode.py from the shared Python tables.\n'
text += '// Character data: Sacremoses 0.2.0, copyright (c) 2020 alvations (MIT).\n'
text += '// See LICENSE-SACREMOSES.\n#pragma once\n#include <utility>\n'
text += 'namespace kitten_text_processing::detail {\n'
text += 'inline constexpr std::pair<char32_t,char32_t> alpha_ranges[] = {\n'
text += ''.join(f'    {{{a}, {b}}},\n' for a,b in ALPHA_RANGES)
text += '};\ninline constexpr char32_t currency_symbols[] = {\n    '
text += ', '.join(str(ord(c)) for c in CURRENCY_SYMBOLS) + '\n};\n}\n'
path.write_text(text)
